(* Top Level *)
program         = "mod" IDENT , { declaration } ;

declaration     = fn_decl
                | struct_decl
                | record_decl
                | interface_decl
                | enum_decl
                | variant_decl
                | alias_decl
                | const_decl ;

(* Declarations *)
fn_decl         = { annotation } , "fn" , [ receiver ] , IDENT , [ type_params ] ,
                  "(" , [ param_list ] , ")" , [ return_type ] , block ;
receiver        = "[" , IDENT , type , "]" ;
param_list      = param , { "," , param } ;
param           = IDENT , type , [ "..." ] ;
return_type     = type , { "," , type } ;

struct_decl     = "struct" , IDENT , [ type_params ] , [ "is" , interface_list ] ,
                  "{" , struct_body , "}" ;
struct_body     = { field_decl }
                  , { init_decl } ;

record_decl     = "record" , IDENT , [ type_params ] ,
                  "{" , record_body , "}" ;
record_body     = { field_decl } ;
field_decl      = [ { field_qualif } ], type , IDENT ;
field_qualif    = ( "pub" | "const" ) ;
init_decl       = "init" , "(" , [ param_list ] , ")" , block ;

interface_decl  = "interface" , IDENT , [ type_params ] ,
                  "{" , { interface_member } , "}" ;
interface_member = fn_sig | const_decl ;
fn_sig          = "fn" , IDENT , "(" , [ param_list ] , ")" , [ return_type ] ;
interface_list  = type , { "," , type } ;

enum_decl       = "enum" , IDENT , "{" , enum_variant , { enum_variant } , "}" ;
enum_variant    = IDENT , [ "(" , param_list , ")" ] ;

variant_decl      = "variant" , IDENT , "{" , variant_field , { variant_field } , "}" ;
variant_field     = type , IDENT ;

alias_decl      = "alias" , IDENT , "=" , type ;
const_decl      = "const" , type , IDENT , "=" , expr ;

annotation      = "@" , IDENT , [ "(" , string_lit , ")" ] ;

(* Types *)
type            = base_type , [ "?" ], [ "!" ]
                | fn_type
                | array_type ;
base_type       = IDENT , [ type_args ] ;
type_args       = "<" , type , { "," , type } , ">" ;
type_params     = "<" , IDENT , { "," , IDENT } , ">" ;
fn_type         = "fn" , "(" , [ type , { "," , type } ] , ")" , [ return_type ] ;
array_type      = type , "[" , "]" ;

(* Statements *)
block           = "{" , NEWLINE, { stmt, NEWLINE } , "}" ;
stmt            = var_decl
                | return_stmt
                | if_stmt
                | for_stmt
                | do_stmt
                | switch_stmt
                | expr_stmt
                | raise_stmt ;

NEWLINE         = "\n", { "\n" } ;

var_decl        = ident_list , ":=" , expr_list ;
ident_list      = IDENT , { "," , IDENT } ;
expr_list       = expr , { "," , expr } ;

return_stmt     = "return" , [ expr_list ] ;
raise_stmt      = "raise" , expr ;

if_stmt         = "if" , expr , block , [ "else" , ( if_stmt | block ) ] ;

for_stmt        = "for" , ident_list , "in" , expr , block ;

do_stmt         = "do", block, "while", expr ;

switch_stmt      = "switch" , expr , "{" , { switch_arm }, switch_default , "}" ;
switch_arm       = switch_pattern , "=>" , ( expr | block ) ;
switch_default   = "default", "=>", ( expr | block ) ;
switch_pattern   = expr, [ "(", param_list, ")" ] ;

expr_stmt       = expr ;

(* Expressions *)

expr            = ternary_expr ;

ternary_expr    = assign_expr , [ "?" , expr , ":" , ternary_expr ] ;

assign_expr     = or_expr, { "=", or_expr } ;

or_expr         = and_expr , { "or" , and_expr } ;

and_expr        = equality_expr , { "and" , equality_expr } ;

equality_expr   = relational_expr , { ( "==" | "!=" ) , relational_expr } ;

relational_expr = coalesce_expr , { ( "<" | ">" | "<=" | ">=" ) , coalesce_expr } ;

coalesce_expr   = additive_expr , { "??" , ( block | additive_expr ) } ;

additive_expr   = mult_expr , { ( "+" | "-" ) , mult_expr } ;

mult_expr       = unary_expr , { ( "*" | "/" | "%" ) , unary_expr } ;

unary_expr      = ( "-" | "!" ) , unary_expr
                | catch_expr ;

catch_expr      = postfix_expr , [ "catch" , IDENT , block ] ;

postfix_expr    = primary_expr , { postfix_suffix } ;
postfix_suffix  = "." , IDENT                           (* field access *)
                | "." , IDENT , "(" , [ arg_list ] , ")"  (* method call *)
                | "(" , [ arg_list ] , ")"              (* function call *)
                | "[" , expr , "]"                      (* index *)
                | "!"                                   (* force-unwrap failable *)
                | "?"                                   (* optional chaining    *) ;

primary_expr    = new_expr
                | closure_expr
                | self_field
                | literal
                | IDENT
                | "(" , expr , ")" ;


new_expr        = "new" , base_type , "(" , [ arg_list ] , ")" ;

catch_expr      = expr , "catch" , IDENT , block ;

closure_expr    = "fn" , "(" , [ param_list ] , ")" , [ return_type ] , block ;

self_field      = "@" , IDENT ;

(* Literals *)
literal         = int_lit | float_lit | string_lit | bool_lit | array_lit | none_lit ;
int_lit         = DIGIT , { DIGIT } ;
float_lit       = DIGIT , { DIGIT } , "." , DIGIT , { DIGIT } ;
string_lit      = '"' , { any_char } , '"' ;
bool_lit        = "true" | "false" ;
array_lit       = "[" , [ expr , { "," , expr } ] , "]" ;
map_lit         = "{", [ map_pair, { ",", map_pair } ], "}" ;
map_pair        = expr, ":", expr ;
none_lit        = "none" ;

(* Primitives *)
IDENT           = LETTER , { LETTER | DIGIT | "_" } ;
LETTER          = "a" - "z" | "A" - "Z" ;
DIGIT           = "0" - "9" ;
